- name: Configure webserver with nginx and tls
  hosts: webservers
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key.file
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/nginx.conf
    server_name: localhost
  tasks:
    - name: install epel-release
      yum:
        name: epel-release
        update_cache: yes
        state: present
    - name: install nginx
      yum:
        name: nginx
        update_cache: yes
        state: installed
    - name: create directory for ssl certificates
      file: 
        path: /etc/nginx/ssl
        state: directory
    - name: copy TLS key
      copy:
        src: files/nginx.key
        "dest": "{{ key_file }}"
        owner: root
        mode: 0600
    - name: copy TLS certificate
      copy:
        src: files/nginx.crt
        "dest": "{{ cert_file }}"
      notify: restart nginx
    - name: copy nginx config file
      copy:
        src: files/nginx.conf
        "dest": "{{ conf_file }}"
    - name: copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644
    - name: eneble/restart nginx
      service:
        name: nginx
        enabled: yes
        state: restarted

